### ISSUE TITLE
Bill showing incorrect actions/status

### ISSUE THREAD

**Issue by saritonin** [nysenate/NYSenate.gov-Website-D9#241]
https://www.nysenate.gov/legislation/bills/2021/S5356 has lost some information about actions/status. It was vetoed (compare with archive at https://web.archive.org/web/20230605165549/https://www.nysenate.gov/legislation/bills/2021/S5356#accordion-actions) but currently says Archive: Last Bill Status -Passed Senate & Assembly

**Comment by routinet** [comment]
Thanks for taking the time to report this.  I have triggered a re-import of bill 2021-S5356 and have verified it is now showing the correct status and action history.  

Closing as completed.
