### ISSUE TITLE
`/district/` pages no longer exist

### ISSUE THREAD

**Issue by evadecker** [nysenate/NYSenate.gov-Website-D9#41]
Previously, there were pages available on nysenate.gov for individual senate districts. The URLs matched this format: `https://www.nysenate.gov/district/${district}`, e.g. https://www.nysenate.gov/district/13. These pages no longer exist, and now redirect to the https://www.nysenate.gov homepage.

The [NYC Boundaries Map](https://github.com/BetaNYC/nyc-boundaries), an open source tool I help maintain, relies on these `/district/` links to direct users to accompanying information when they query a particular district. An [issue was filed in our repo](https://github.com/BetaNYC/nyc-boundaries/issues/89) in August flagging this problem.

Are there new `/district/` pages that are available? If not, could they be reintroduced?

**Comment by routinet** [comment]
Thanks for reporting this.  We do have an internal open ticket to address this already, and this report was a topic of discussion this morning with our team.  A fix to restore the `/district/xx` URLs is in process.  I do not have an ETA yet, but it should not be a long wait.

In the meantime, the district maps are available from the individual microsites, found at `/senators/<senator-name>/district`.

**Comment by evadecker** [comment]
Thanks for the quick reply @routinet and glad to hear they'll be back soon!

**Comment by lavingiasa** [comment]
Amazing, thank you both!

**Comment by routinet** [comment]
PR#46 https://github.com/nysenate/NYSenate.gov-Website-D9/pull/46 addresses this issue, pending review/deployment.

**Comment by evadecker** [comment]
Looks like #46 was merged and the `/district/` pages are present again! Thanks so much for adding this back!
